### ISSUE TITLE
Investigate slow tests in L0

### ISSUE THREAD

**Issue by yizhuoz004** [NVIDIA/TensorRT-Incubator#118]
Observed this test again to take much more time than expected:
```
248.59s call     tests/test_internal_docs.py::test_python_code_snippets[/tripy/docs/pre0_user_guides/00-introduction-to-tripy.md]
```

See an example L0 run: https://github.com/NVIDIA/TensorRT-Incubator/actions/runs/10412448107/job/28838233963?pr=110

**Comment by yizhuoz004** [comment]
For all unit tests: https://github.com/NVIDIA/TensorRT-Incubator/actions/runs/10468632197/job/28989953348

**Comment by yizhuoz004** [comment]
It seems the overhead comes from `exec()`. I tested an example which runs at 4 sec directly, but in `exec(code, {}, {})`, it took 16 sec.

**Comment by pranavm-nvidia** [comment]
Some improvements here: https://github.com/NVIDIA/TensorRT-Incubator/pull/156

**Comment by pranavm-nvidia** [comment]
@yizhuoz004 I think this is probably resolved now?
