### ISSUE TITLE
Fix Tensor.tolist()

### ISSUE THREAD

**Issue by yizhuoz004** [NVIDIA/TensorRT-Incubator#134]
`memoryview(memref).tolist()` does not print the values as expected for some dtypes, such as `bfloat16, float8`.
Also consider move `tolist()` and `pretty_print` APIs to MLIR-TRT's python bindings.

**Comment by yizhuoz004** [comment]
Also the float16 memoryview cannot return nested lists:
```
>>> a = np.ones((2, 2), dtype=np.float16)
>>> b = tp.Tensor(a)
>>> b
tensor(
    [1.0000, 1.0000, 1.0000, 1.0000],
    dtype=float16, loc=gpu:0, shape=[2, 2])
```

**Comment by pranavm-nvidia** [comment]
@yizhuoz004 does #95 resolve this?

**Comment by yizhuoz004** [comment]
> [@yizhuoz004](https://github.com/yizhuoz004) does [#95](https://github.com/NVIDIA/TensorRT-Incubator/pull/95) resolve this?

No this is still open.

**Comment by pranavm-nvidia** [comment]
I think https://github.com/NVIDIA/TensorRT-Incubator/pull/254 addresses this. Do we still want to consider moving `tolist` and `pretty_print` to MLIR-TRT?

**Comment by yizhuoz004** [comment]
Not necessary for now. Let's close this issue.
