### ISSUE TITLE
Performance improvements in Tripy

### ISSUE THREAD

**Issue by parthchadha** [NVIDIA/TensorRT-Incubator#159]
- [x] Re-enable use of cuda streams
- [ ] Make Tripy execution async by default
- [ ] Benchmark performance and measure overheads introduced by Tripy executor.

**Comment by pranavm-nvidia** [comment]
We also need to a systematic approach to guarding against perf regressions. Maybe one approach we can take is to have some method of estimating how long each MLIR op would take (obviously easier said than done given compiler optimizations, fusions etc.). That way we won't actually need to compile+run every test, and can just ensure that we generate performant MLIR.

**Comment by jhalakpatel** [comment]
We could add the following: Implement a non-DPS style calling convention in MLIR-TensorRT to avoid extra memory allocation and device-to-device memory copy.

**Comment by parthchadha** [comment]
Closing this issue and tracking this work as part of https://github.com/NVIDIA/TensorRT-Incubator/milestone/1.
