### ISSUE TITLE
Add tp.cumsum

### ISSUE THREAD

**Issue by parthchadha** [NVIDIA/TensorRT-Incubator#164]
https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html
https://pytorch.org/docs/stable/generated/torch.cumsum.html

**Comment by pranavm-nvidia** [comment]
We should be able to implement this as `transpose(transpose(x) @ triu(ones_like(x)))`.

**Comment by pranavm-nvidia** [comment]
https://github.com/NVIDIA/TensorRT-Incubator/pull/205
