### ISSUE TITLE
Add strict flag to `model.load_state_dict`

### ISSUE THREAD

**Issue by farazkh80** [NVIDIA/TensorRT-Incubator#296]
To avoid having unloaded weights, we should support `strict` flag for `model.load_state_dict` in case some weights are missing in the state dict being loaded similar to [torch](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.load_state_dict).

**Comment by yizhuoz004** [comment]
Also addressed by #340
