### ISSUE TITLE
Parameters disappear from `state_dict` after `load_state_dict`

### ISSUE THREAD

**Issue by farazkh80** [NVIDIA/TensorRT-Incubator#317]
Parameters disappear from `state_dict` after `load_state_dict`. 

Example
```python
import tripy as tp

lay = tp.Linear(2,3)
assert 'weight' in set(lay.state_dict().keys())

lay.load_state_dict({'weight': tp.ones((3,2), dtype=tp.float32)})
assert 'weight' in set(lay.state_dict().keys()) # fails
```

**Comment by yizhuoz004** [comment]
This is because the data in state_dict is not a `tp.Parameter`, instead with
```py
lay.load_state_dict({'weight': tp.Parameter(np.ones((3, 2), dtype=np.float32))})
```
it works fine.

@pranavm-nvidia Do you think we should convert everything in an external state_dict to `tp.Parameter` by default or just raise an error?

**Comment by pranavm-nvidia** [comment]
Let's automatically convert I think? I also noticed that torch will warn about missing/extra keys, which I don't think we currently do. Would be nice to add some checks for that as well.
