### ISSUE TITLE
LinspaceOp won't work properly on trt10.5

### ISSUE THREAD

**Issue by zezhang** [NVIDIA/TensorRT-Incubator#320]
For the following IR (`linspace` op with dynamic shape):

```
  func.func @group0(%arg0: tensor<?x32xf32> {tensorrt.shape_profile = #tensorrt.shape_profile<min = [1, 32], opt = [64, 32], max = [64, 32]>}) -> tensor<?xf32> {
      %cst_i32 = tensorrt.constant dense<0> : tensor<1xi32>
      %0 = tensorrt.shape %arg0 : tensor<?x32xf32> -> tensor<2xi32>
      %1 = tensorrt.gather {axis = 0 : i64} ins(%0, %cst_i32 : tensor<2xi32>, tensor<1xi32>) -> tensor<1xi32>
      %2 = tensorrt.linspace[ 0.000000e+00] [%1 : tensor<1xi32>] [ 1.000000e+00] : tensor<?xi32>
      %3 = tensorrt.identity %2 : tensor<?xi32> to tensor<?xf32>
      return %3 : tensor<?xf32>
  }
```

Calling `TranslateToTensorRTEnginePass` gives me following error on `TensorRT version 10.5`

`INetworkDefinition::addFill(Dims const&, FillOperation, DataType): Error Code 3: API Usage Error (Parameter check failed, condition: isValidDims(dimensions). )`

However, the exact same IR works well with `TensorRT version 8.6.`

Could you please take a look?

**Comment by joshpnv** [comment]
tagging @shelkesagar29

**Comment by shelkesagar29** [comment]
Hi @zezhang 
Thanks for raising the issue.
I have submitted the fix https://github.com/NVIDIA/TensorRT-Incubator/pull/332

**Comment by zezhang** [comment]
Thanks for the quick response! The fix works.

**Comment by christopherbate** [comment]
Closing issue, thanks!
