### ISSUE TITLE
Enable function registry for methods

### ISSUE THREAD

**Issue by pranavm-nvidia** [NVIDIA/TensorRT-Incubator#338]
When we decorate a class with a function registry (e.g. `export.public_api()`) we should apply it to all methods of that class. This allows us to support features like type checking and overloading for methods. 

We can implement this by updating the function registry decorator to recursively call itself on each method of the class. The key we call it with will need to include the class name as well as the method name, or we will get collisions quickly. We may need to update `get_callee_func_name` to strip out the class name so we can add column information. To test this, we can check the stack information of a tensor produced by a Module's `__call__` method to ensure it contains accurate column ranges.

**Comment by slyubomirsky** [comment]
Regarding the `__call__` on a method example, I'm not sure there is a great way to register all the methods on a class without ignoring magic methods without unleashing chaos. Namely, if we want to process all the magic methods in something like `export.public_api`, many of them will cause errors due to not having type annotations written out. For magic methods, we might want to use a whitelist for those that make sense.

**Comment by pranavm-nvidia** [comment]
@slyubomirsky I assumed there might be some way to determine which methods are implemented/overridden by a child class. Another way would be to only apply this to methods with docstrings (i.e. public facing methods).

**Comment by slyubomirsky** [comment]
I'll see if there's a way to check for overrides specifically with `inspect`. Docstrings are a good idea too, perhaps that will be the way to go.

**Comment by slyubomirsky** [comment]
I think checking for a docstring might be safer because of another edge case that comes up: methods added by decorators. For example, `@dataclass` adds implementations of `__eq__`, etc., and it is not done by inheritance. We could probably detect that case but others like it might come up.

**Comment by slyubomirsky** [comment]
Implemented.
