### ISSUE TITLE
Segfault in prompt_encoder

### ISSUE THREAD

**Issue by yizhuoz004** [NVIDIA/TensorRT-Incubator#378]
[prompt_encoder.txt](https://github.com/user-attachments/files/17760086/prompt_encoder.txt)

**Comment by shelkesagar29** [comment]
This is issue in upstream stablehlo pass.
It converts the following IR 
```
%3 = stablehlo.subtract %c_19, %c_37 : (tensor<1x1xi32>, tensor<1x1xi32>) -> tensor<?x?xi32>
  %4 = plan.with_shape %3(%c1_i32, %c1_i32) : (tensor<?x?xi32>, i32, i32) -> tensor<?x?xi32>
```
to
```
%57 = "stablehlo.constant"() <{value = dense<-1> : tensor<1x1xi32>}> : () -> tensor<1x1xi32>
  %58 = "plan.with_shape"(%57, %20, %20) : (tensor<1x1xi32>, i32, i32) -> tensor<?x?xi32>
```

However, if op is replaced with constant and consumer is non stablehlo op, `tensor.cast` should be used which is missing.

**Comment by shelkesagar29** [comment]
PR https://github.com/NVIDIA/TensorRT-Incubator/pull/401
provides Stablehlo patch that resolves this issue.
I tested IR on `SHLO -> Executable` pipeline and it runs successfully.
