### ISSUE TITLE
Parameters in Module Containers Not Retained in state_dict after modification

### ISSUE THREAD

**Issue by farazkh80** [NVIDIA/TensorRT-Incubator#386]
When a module contains a container (e.g., list) of parameters, replacing a parameter inside that container with a non-parameter

```python
module.param_list[0] = tp.ones(...)) 
```

causes it to disappear from the `module.state_dict`.

We could prevent changing a `Parameter` attr of a module into a `non-Parameter`, but this is not easy for members of collections

**Comment by pranavm-nvidia** [comment]
@farazkh80 Is this resolved? If not, can we reopen this issue? The behavior is confusing right now since we automatically convert to `Parameter`s except for items in collections
